import { useState, useCallback } from "react";
import type { AnalysisState } from "../types";

const INITIAL_STATE: AnalysisState = {
  phase: "idle",
  repoMeta: null,
  languages: [],
  contributors: [],
  release: null,
  depHealth: null,
  vulnerabilities: [],
  score: null,
  signals: null,
  aiNarrative: {},
  error: null,
};

export function useAnalysis() {
  const [state, setState] = useState<AnalysisState>(INITIAL_STATE);

  const analyze = useCallback(async (url: string) => {
    setState({ ...INITIAL_STATE, phase: "loading" });

    let aiBuffer = "";
    let streamBuffer = "";

    try {
      const response = await fetch("/api/analyze", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ url }),
      });

      if (!response.ok) {
        const errJson = await response.json().catch(() => ({}));
        throw new Error(errJson.error || "Analysis request failed");
      }

      setState(s => ({ ...s, phase: "phase1" }));

      const reader = response.body!.getReader();
      const decoder = new TextDecoder();

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;

        streamBuffer += decoder.decode(value, { stream: true });
        const lines = streamBuffer.split("\n");
        // Keep the last partial line in the buffer
        streamBuffer = lines.pop() || "";

        for (const line of lines) {
          const trimmed = line.trim();
          if (!trimmed.startsWith("data: ")) continue;

          const eventData = trimmed.slice(6).trim();
          if (!eventData) continue;

          let event: any;
          try {
            event = JSON.parse(eventData);
          } catch (e) {
            console.warn("Failed to parse event JSON:", eventData, e);
            continue;
          }

          switch (event.type) {
            case "repo_meta":
              setState(s => ({ ...s, repoMeta: event.data }));
              break;
            case "languages":
              setState(s => ({ ...s, languages: event.data }));
              break;
            case "contributors":
              setState(s => ({ ...s, contributors: event.data }));
              break;
            case "release":
              setState(s => ({ ...s, release: event.data }));
              break;
            case "dep_health":
              setState(s => ({ ...s, depHealth: event.data, phase: "phase2" }));
              break;
            case "vulnerabilities":
              setState(s => ({ ...s, vulnerabilities: event.data }));
              break;
            case "score":
              setState(s => ({ ...s, score: event.data }));
              break;
            case "signals":
              setState(s => ({ ...s, signals: event.data }));
              break;
            case "ai_chunk":
              aiBuffer += event.chunk;
              try {
                // If it's valid JSON (or partially parsed JSON), update state
                // Since AI sends streaming JSON tokens, we try to parse it.
                // Note: parsing partial JSON requires careful parsing. Let's make a simple partial JSON parser,
                // or wait for complete keys, or try to clean up the JSON.
                const parsed = parsePartialJson(aiBuffer);
                if (parsed) {
                  setState(s => ({ ...s, aiNarrative: parsed, phase: "phase3" }));
                }
              } catch {
                // Keep buffering
              }
              break;
            case "done":
              setState(s => ({ ...s, phase: "done" }));
              break;
            case "error":
              setState(s => ({ ...s, phase: "error", error: event.message }));
              break;
          }
        }
      }
    } catch (err: any) {
      setState(s => ({ ...s, phase: "error", error: err.message }));
    }
  }, []);

  const reset = useCallback(() => setState(INITIAL_STATE), []);

  return { ...state, analyze, reset };
}

// A simple helper to parse incomplete JSON strings generated by the streaming model
function parsePartialJson(jsonStr: string): any {
  let cleaned = jsonStr.trim();
  if (!cleaned) return null;

  // If it's complete, just parse it
  try {
    return JSON.parse(cleaned);
  } catch (e) {}

  // If it's incomplete, let's close open objects/arrays/quotes to see if it parses
  let openBraces = 0;
  let openBrackets = 0;
  let inString = false;
  let escape = false;

  for (let i = 0; i < cleaned.length; i++) {
    const char = cleaned[i];
    if (escape) {
      escape = false;
      continue;
    }
    if (char === "\\") {
      escape = true;
      continue;
    }
    if (char === '"') {
      inString = !inString;
      continue;
    }
    if (inString) continue;

    if (char === "{") openBraces++;
    else if (char === "}") openBraces--;
    else if (char === "[") openBrackets++;
    else if (char === "]") openBrackets--;
  }

  let suffix = "";
  if (inString) suffix += '"';
  while (openBrackets > 0) {
    suffix += "]";
    openBrackets--;
  }
  while (openBraces > 0) {
    suffix += "}";
    openBraces--;
  }

  try {
    return JSON.parse(cleaned + suffix);
  } catch (e) {
    // If that still fails, let's try to extract key-value pairs manually using regex
    // since we know the keys and structure.
    const result: any = {};
    const keys = ["architectureObservations", "libraryChoices", "securityFlags", "quickWins", "mentorSummary"];

    for (const key of keys) {
      if (key === "quickWins") {
        const match = cleaned.match(/"quickWins"\s*:\s*\[([\s\S]*?)\]?/);
        if (match) {
          const itemsStr = match[1];
          const items = itemsStr
            .split(",")
            .map(s => s.trim().replace(/^"/, "").replace(/"$/, "").trim())
            .filter(s => s.length > 0);
          result.quickWins = items;
        }
      } else {
        const regex = new RegExp(`"${key}"\\s*:\\s*"([\\s\S]*?)(?:"|$)`);
        const match = cleaned.match(regex);
        if (match) {
          result[key] = match[1].replace(/\\n/g, "\n").replace(/\\"/g, '"');
        }
      }
    }
    return Object.keys(result).length > 0 ? result : null;
  }
}
